# Pfad zu deiner HytaleServer.jar und Assets.zip
hytale_server_jar=C:/Users/gaukh/AppData/Roaming/Hytale/install/release/package/game/latest/Server/HytaleServer.jar
hytale_assets_zip=C:/Users/gaukh/AppData/Roaming/Hytale/install/release/package/game/latest/Assets.zip
hytale_singleplayer_mods=C:/Users/gaukh/AppData/Roaming/Hytale/UserData/Mods